/**
 * HR_API
 * Manages Employees
 *
 * OpenAPI spec version: 1.0
 * Contact: t.s@sb.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.InlineResponse200
import io.swagger.client.model.InlineResponse404
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * Deletes users from db.
   * 
   * Expected answers:
   *   code 200 :  (OK)
   *   code 404 : InlineResponse404 (Endpoint Not found Please make sure you have the right endpoint)
   */
  def userDelete(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "https://virtserver.swaggerhub.com/SE-Design/HR_Temil24/1.0", "/user", "application/json")
      .withSuccessResponse[Unit](200)
      .withErrorResponse[InlineResponse404](404)
        /**
   * Gets Users from employee db.
   * 
   * Expected answers:
   *   code 200 : InlineResponse200 (OK)
   * 
   * @param name employee
   */
  def userGet(name: String): ApiRequest[InlineResponse200] =
    ApiRequest[InlineResponse200](ApiMethods.GET, "https://virtserver.swaggerhub.com/SE-Design/HR_Temil24/1.0", "/user", "application/json")
      .withQueryParam("name", name)
      .withSuccessResponse[InlineResponse200](200)
      

}

