/**
 * HR_API
 * Manages Employees
 *
 * OpenAPI spec version: 1.0
 * Contact: t.s@sb.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class InlineResponse404 (
  message: Option[String] = None
) extends ApiModel


